apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuapp2
  namespace: teste-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teste-app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: joaofstn323/app2:latest
          ports:
            - containerPort: 8080