apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: teste-app2
images:
- name: goapp
  newName: joaofstn323/app2
  newTag: ce1842e4ae972468c73e44b328c0fc2aeb2da80f
- name: joaofstn323/app2
  newName: joaofstn323/app2
  newTag: latest
