apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
namespace: teste-app2
images:
  - name: app2
    newName: joaofstn323/app2
    newTag: latest