apiVersion: v1
kind: Service
metadata:
  name: meuapp2
  namespace: teste-app2
spec:
  type: ClusterIP
  selector:
    app: app2
  ports:
    - port: 80
      targetPort: 8080 # Porta no contêiner que está escutando
